config/routes.rb
Rails.application.routes.draw do

  root'hoockup#setup'

  get'hoockup/getcode'
  post'hoockup/getcode'
  
  get'hoockup/callback'
  post'hoockup/callback'

  get'apicontrol/apicontrol'
  post'apicontrol/apicontrol'

  get'sendmail/sendmail'
  post'sendmail/sendmail'

  

end

app/controllers/apicontrol_controller.rb
require 'http'
require 'json'
require 'date'
include ConnectHttp

class ApicontrolController < ApplicationController
 

  def apicontrol #accessguest呼び出しアクション作成,表用のデータ抽出
    authtoken = "Bearer " + $access_token
    res = HTTP.headers(:accept => "vnd.lockstate.v1+json",:Authorization => authtoken)
    .get("https://api.lockstate.jp/access_persons?type=access_guest", :ssl_context => CTX)
    @res = ActiveSupport::JSON.decode(res.body)
    
    @res = @res['data'] 
    puts @res
    
   
    return @res
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/connect_http.rb
#必要なのがhttpsなのでSSLを有効にする。とりあえず証明書は無視。
module ConnectHttp
  require 'http'
  #require 'json'
  extend ActiveSupport::Concern
  CTX = OpenSSL::SSL::SSLContext.new
  CTX.verify_mode = OpenSSL::SSL::VERIFY_NONE
end

app/controllers/hoockup_controller.rb
include ConnectHttp
require 'http'
require 'net/https'
require 'time'
CTX = OpenSSL::SSL::SSLContext.new
CTX.verify_mode =OpenSSL::SSL::VERIFY_NONE

class HoockupController < ApplicationController
    
  def setup
  end
  
  def getcode
    @@client = params[:clientId].presence
    @@secret = params[:clientSecret].presence
    @@callbackuri = params[:redirecturi].presence
    
    
    req = 'https://connect.lockstate.jp/oauth/'+'authorize?'+'client_id='+@@client+'&response_type=code&redirect_uri='+@@callbackuri
    redirect_to req
  end 
  
  def callback
   tmp_token = params[:code]
   postform = {'code' => tmp_token \
   ,'client_id' => @@client \
   ,'client_secret' => @@secret \
   ,'redirect_uri' => @@callbackuri \
   ,'grant_type' => 'authorization_code'}
  
   res = HTTP.headers("Content-Type" => "application/x-www-form-urlencoded")
   .post("https://connect.lockstate.jp/oauth/token", :ssl_context => CTX , :form => postform)
   
   @res = ActiveSupport::JSON.decode(res) #アクセストークン確認用
   puts @res
   j = ActiveSupport::JSON.decode(res)
   $access_token = j["access_token"]
 
   if res.code!=200
    @res = res
     @error = res
　   @state = "認証に失敗しました"
　   render
   else 
   @res = res
   @error = ""
     @state = "認証に成功しました"
     render
   end 

  end #callback defのend

end #クラスのend

app/controllers/sendmail_controller.rb
require 'http'
require 'json'
require 'date'
include ConnectHttp

class SendmailController < ApplicationController
 

  def sendmail
    
    #id受け渡し確認用コード(APIにうけわたされているかどうかを確認する必要がある。)
    #puts($list) 
    
    #こっからforループ
    
    for id in $list do
    
    authtoken = "Bearer " + $access_token
    res = HTTP.headers(:accept => "vnd.lockstate.v1+json",:Authorization => authtoken)
    .post("https://api.lockstate.jp/access_persons/" + id + "/email/notify",:ssl_context => CTX)
    
    end
    
    return res #これいるかな？
    
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/apicontrol_helper.rb
module ApicontrolHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoockup_helper.rb
module HoockupHelper
end

app/views/apicontrol/apicontrol.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">

<p>アクセスユーザー一覧</p>

<% $list=[] %>

<% @res.each do |guest| %>

<table border =1 cellspacing="0" cellpadding="3">
<tr>
<td width="300" height="1"><p>name</p></td>
<td width="300" height="1"><p>利用開始時刻</p></td>
<td width="300" height="1"><p>利用終了時刻</p></td>
<td width="300" height="1"><p>現在時刻</p></td>
<td width="300" height="1"><p>id</p></td>
<td width="300" height="1"><p>メールアドレス</p></td>
<td width="300" height="1"><p>メール</p></td>
</tr>
<th width="450" height="1"><%= guest["attributes"]["name"] %> </th>
<% start = guest["attributes"]["starts_at"]%>
<td width="450" height="1"><%= DateTime.parse(start)%></td>
<td width="450" height="1"><%= guest["attributes"]["ends_at"] %> </td>
<% time = DateTime.now %>
<td width="450" heigth="1"><%= time %> </td>
<td width="450" height="1"><%= guest["id"] %></td>
<td width="450" height="1"><%= guest["attributes"]["email"] %> </td>
<td width="450" height="1" color="red">
<% sabun = DateTime.parse(start)-DateTime.now
   @maru = ""
   if(sabun)<45 and (sabun)>30
   @maru="○"
   $list.push(guest["id"])
   else
   
   end %>
<%= @maru%>
</td>
</table>

<% end %>

<%= link_to "送信", sendmail_sendmail_path($list) %>



</div>

app/views/hoockup/callback.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
 <%= form_tag apicontrol_apicontrol_path do %> 
  <h2>ConnectAPIの認証結果</h2>
    <p><%= @state %></p>
    <p><%= @error %></p>
    <input type="submit" value = "アクセスゲスト一覧表示">
 <%end%>
</div>

app/views/hoockup/getcode.html.erb
<h1>Hoockup#getcode</h1>
<p>Find me in app/views/hoockup/getcode.html.erb</p>

app/views/hoockup/setup.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
    <h2>Aouth認証</h2>
    <p>以下に、認証情報を入力してください</p>
</div>

<div style= "text-align:center;line-height:100%;padding:10px;">
    <!--getocode.htmlに送信-->
    <%= form_tag hoockup_getcode_path do %>
    
    <p>クライアントID</p>
    <!--<input type="text" class="form-control title-field" name="clientId" style="width:500px" value="b0e0f164abc0b47134b42efa8927082cdaeff8a59b6591eaaa73caf9df2b12e1">-->
    <input type="text" class="form-control title-field" name="clientId" style="width:500px" value="0b77bce4e984ce08387312102f2cbc3d9528a7719183a441a2b9becb76379c88">
    <p>クライアントシークレット</p>
    <!--<input type="text" class="form-control title-field" name="clientSecret" style="width:500px" value="b6ab60a1647db4771e025e07e3de73e06eee7c134bbe11a88df507885c666842">-->
    <input type="text" class="form-control title-field" name="clientSecret" style="width:500px" value="a79e67cc0d3b885b97da3db10dc7d01006fcc23d96a805f3b2f3af54a46d94dd">
    <p>承認済みのリダイレクト</p>
    <input type="text" class="form-control title-field" name="redirecturi" style="width:500px" value="https://practice2-tadashinakamura.c9users.io/hoockup/callback">
    
    <input type="submit" value="送信">
    
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sendmail/sendmail.html.erb
<p>送信完了！！</p>